import path from "node:path";
import fs from "node:fs/promises";

import {
  checkGhAuth,
  checkTargetRepoGitIdentity,
  getGitOutput,
  runGh,
  runGit,
} from "../utils/git";

const VAULT_DIR = process.env.VAULT_DIR;
const TARGET_REPO_DIR = process.env.TARGET_REPO_DIR;
const TARGET_CONTENT_DIR = process.env.TARGET_CONTENT_DIR || "data/blog";

if (!VAULT_DIR) throw new Error("Missing env: VAULT_DIR");
if (!TARGET_REPO_DIR) throw new Error("Missing env: TARGET_REPO_DIR");

const vaultRoot = path.resolve(VAULT_DIR);
const targetRepoRoot = path.resolve(TARGET_REPO_DIR);
const manifestDir = path.join(vaultRoot, "manifest");
const reviewIndexPath = path.join(manifestDir, "review-index.json");

type ReviewStatus = "pending" | "ready" | "published";
type PublishAction = "created" | "updated" | "unchanged";

type ReviewIndexItem = {
  title: string;
  displayTitle?: string;
  status: ReviewStatus;
  draftPath: string;
  reviewPath: string;
  readyPath?: string;
  sourcePath?: string;
  targetPath?: string;
  submittedAt: string;
  checkedAt?: string;
  publishedAt?: string;
  publishBranch?: string;
  publishAction?: PublishAction;
  commit?: string;
  prNumber?: number;
  prUrl?: string;
};

async function pathExists(filePath: string) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function readReviewIndex(): Promise<ReviewIndexItem[]> {
  if (!(await pathExists(reviewIndexPath))) {
    throw new Error(`review-index.json not found: ${reviewIndexPath}`);
  }

  return JSON.parse(await fs.readFile(reviewIndexPath, "utf-8"));
}

async function writeReviewIndex(items: ReviewIndexItem[]) {
  await fs.mkdir(manifestDir, { recursive: true });
  await fs.writeFile(reviewIndexPath, JSON.stringify(items, null, 2), "utf-8");
}

function formatDateTime() {
  const date = new Date();
  const yyyy = date.getFullYear();
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const dd = String(date.getDate()).padStart(2, "0");
  const hh = String(date.getHours()).padStart(2, "0");
  const mi = String(date.getMinutes()).padStart(2, "0");
  return `${yyyy}${mm}${dd}-${hh}${mi}`;
}

function parsePrNumber(prUrl: string) {
  const match = prUrl.match(/\/pull\/(\d+)/);
  return match ? Number(match[1]) : undefined;
}

async function readFileIfExists(filePath: string) {
  if (!(await pathExists(filePath))) {
    return null;
  }

  return fs.readFile(filePath, "utf-8");
}

async function copyIfChanged(params: {
  sourcePath: string;
  targetPath: string;
}): Promise<PublishAction> {
  const { sourcePath, targetPath } = params;

  const sourceContent = await fs.readFile(sourcePath, "utf-8");
  const targetContent = await readFileIfExists(targetPath);

  if (targetContent === null) {
    await fs.mkdir(path.dirname(targetPath), { recursive: true });
    await fs.writeFile(targetPath, sourceContent, "utf-8");
    return "created";
  }

  if (targetContent === sourceContent) {
    return "unchanged";
  }

  await fs.writeFile(targetPath, sourceContent, "utf-8");
  return "updated";
}

function getDefaultTargetPath(item: ReviewIndexItem) {
  if (!item.readyPath) {
    throw new Error(`Missing readyPath: ${item.title}`);
  }

  return path.join(TARGET_CONTENT_DIR, path.basename(item.readyPath));
}

function buildPrBody(items: ReviewIndexItem[]) {
  const createdItems = items.filter((item) => item.publishAction === "created");
  const updatedItems = items.filter((item) => item.publishAction === "updated");

  const renderList = (list: ReviewIndexItem[]) => {
    if (list.length === 0) return ["- None"];
    return list.map((item) => `- ${item.displayTitle || item.title}`);
  };

  return [
    "## Publish Summary",
    "",
    `Published: ${items.length}`,
    "",
    "### Created",
    "",
    ...renderList(createdItems),
    "",
    "### Updated",
    "",
    ...renderList(updatedItems),
    "",
    "---",
    "",
    "### Source",
    "",
    ...items.map((item) => `- ${item.sourcePath || item.reviewPath}`),
    "",
    "---",
    "",
    "Generated by KnowledgeOps.",
  ].join("\n");
}

async function main() {
  await checkTargetRepoGitIdentity(targetRepoRoot);
  await checkGhAuth(targetRepoRoot);

  const reviewIndex = await readReviewIndex();
  const readyItems = reviewIndex.filter((item) => item.status === "ready");

  if (readyItems.length === 0) {
    console.log("No ready items to publish.");
    return;
  }

  const branchName = `publish/${formatDateTime()}`;
  const publishedAt = new Date().toISOString();

  console.log(`Publishing ${readyItems.length} ready item(s)`);
  console.log(`Branch: ${branchName}`);

  await runGit(["checkout", "main"], targetRepoRoot);
  await runGit(["pull", "--ff-only"], targetRepoRoot);
  await runGit(["checkout", "-b", branchName], targetRepoRoot);

  const publishedItems: ReviewIndexItem[] = [];
  let unchangedCount = 0;
  let skippedCount = 0;

  for (const item of readyItems) {
    if (!item.readyPath) {
      console.warn(`Missing readyPath, skipped: ${item.title}`);
      skippedCount++;
      continue;
    }

    const readyAbsPath = path.join(vaultRoot, item.readyPath);

    if (!(await pathExists(readyAbsPath))) {
      console.warn(`Ready file not found, skipped: ${item.readyPath}`);
      skippedCount++;
      continue;
    }

    const targetRelPath = item.targetPath || getDefaultTargetPath(item);
    const targetAbsPath = path.join(targetRepoRoot, targetRelPath);

    const publishAction = await copyIfChanged({
      sourcePath: readyAbsPath,
      targetPath: targetAbsPath,
    });

    if (publishAction === "unchanged") {
      unchangedCount++;
      console.log(`Unchanged: ${item.readyPath}`);
      continue;
    }

    publishedItems.push({
      ...item,
      targetPath: targetRelPath,
      publishedAt,
      publishBranch: branchName,
      publishAction,
    });

    const actionText = publishAction === "created" ? "Created" : "Updated";
    console.log(`${actionText}: ${item.readyPath}`);
    console.log(`  -> ${targetRelPath}`);
  }

  if (publishedItems.length === 0) {
    console.log("");
    console.log("No changed files to publish.");
    console.log(`Unchanged: ${unchangedCount}`);
    console.log(`Skipped: ${skippedCount}`);
    return;
  }

  await runGit(["add", TARGET_CONTENT_DIR], targetRepoRoot);

  const status = await getGitOutput(["status", "--porcelain"], targetRepoRoot);
  if (!status) {
    console.log("No git changes detected. Publish stopped.");
    return;
  }

  const commitMessage = `docs(knowledge): publish ${publishedItems.length} article(s)`;

  await runGit(["commit", "-m", commitMessage], targetRepoRoot);

  const commitHash = await getGitOutput(
    ["rev-parse", "--short", "HEAD"],
    targetRepoRoot
  );

  await runGit(["push", "-u", "origin", branchName], targetRepoRoot);

  const prTitle = `docs(knowledge): publish ${formatDateTime()}`;
  const prBody = buildPrBody(publishedItems);

  const prResult = await runGh(
    [
      "pr",
      "create",
      "--title",
      prTitle,
      "--body",
      prBody,
      "--base",
      "main",
      "--head",
      branchName,
    ],
    targetRepoRoot
  );

  const prUrl = prResult.trim();
  const prNumber = parsePrNumber(prUrl);

  const publishedMap = new Map(
    publishedItems.map((item) => [item.reviewPath, item])
  );

  const nextReviewIndex = reviewIndex.map((item) => {
    const publishedItem = publishedMap.get(item.reviewPath);

    if (!publishedItem) {
      return item;
    }

    return {
      ...item,
      status: "published" as const,
      targetPath: publishedItem.targetPath,
      publishedAt,
      publishBranch: branchName,
      publishAction: publishedItem.publishAction,
      commit: commitHash,
      prNumber,
      prUrl,
    };
  });

  await writeReviewIndex(nextReviewIndex);

  console.log("");
  console.log("Publish completed");
  console.log(`Published: ${publishedItems.length}`);
  console.log(`Unchanged: ${unchangedCount}`);
  console.log(`Skipped: ${skippedCount}`);
  console.log(`Branch: ${branchName}`);
  console.log(`Commit: ${commitHash}`);
  console.log(`PR: ${prUrl}`);
}

main().catch((error) => {
  console.error("Publish failed");
  console.error(error);
  process.exit(1);
});
